proxy:
  title: Shiny Proxy POC
  port: 8080
  container-wait-time: 40000
  authentication: none
  docker:
      internal-networking: true
  specs:
  - id: emissionDashboard
    display-name: Emission Dashboard
    description: Shiny Application for Car Emission.
    container-cmd: ["R", "-e", "shiny::runApp('/root/app')"]
    container-image: app-image
    container-network: sp-network
logging:
  file:
    shinyproxy.log


